# Generated by Django 4.0.3 on 2022-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('socket', models.CharField(max_length=10)),
                ('gen', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cooler',
        ),
    ]
