# Generated by Django 4.0.3 on 2022-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0003_case_cpu_cooler_gpu_motherboard_psu_ram_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='form_supp',
            field=models.IntegerField(),
        ),
    ]
