# Generated by Django 4.0.3 on 2022-03-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0005_pc_parts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PC_PARTS',
        ),
    ]
