# Generated by Django 4.0.3 on 2022-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0007_saved_build'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAVED_BUILD',
        ),
    ]
