# Generated by Django 4.0.2 on 2022-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0009_saved_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPLICATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('CPU', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=100)),
                ('OS', models.CharField(max_length=100)),
                ('GPU', models.CharField(max_length=100)),
                ('STORAGE', models.CharField(max_length=100)),
            ],
        ),
    ]
