# Generated by Django 4.0.2 on 2022-03-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0010_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='STORAGE',
            new_name='DISK_SPACE',
        ),
    ]
