# Generated by Django 4.0.3 on 2022-03-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0011_rename_storage_application_disk_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAIN_BUILD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('CPU', models.CharField(max_length=100)),
                ('CPU_COOLER', models.CharField(max_length=100)),
                ('MOTHERBOARD', models.CharField(max_length=100)),
                ('RAM', models.CharField(max_length=100)),
                ('GPU', models.CharField(max_length=100)),
                ('STORAGE', models.CharField(max_length=100)),
                ('PSU', models.CharField(max_length=100)),
                ('CASE', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procie', models.CharField(max_length=100)),
            ],
        ),
    ]
