# Generated by Django 4.0.3 on 2023-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0012_main_build_test_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Case'},
        ),
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'CPU'},
        ),
        migrations.AlterModelOptions(
            name='cpu_cooler',
            options={'verbose_name': 'CPU Cooler'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name': 'GPU'},
        ),
        migrations.AlterModelOptions(
            name='main_build',
            options={'verbose_name': 'Main Build'},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'verbose_name': 'Motherboard'},
        ),
        migrations.AlterModelOptions(
            name='psu',
            options={'verbose_name': 'PSU'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'RAM'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage'},
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='chipset',
            new_name='gen',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='gen',
        ),
        migrations.AddField(
            model_name='cpu',
            name='gen_code',
            field=models.CharField(default='NOT SET', max_length=10),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='max_mem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(default='NOT  SET', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(default='NOT SET', max_length=10),
        ),
    ]
