# Generated by Django 4.0.3 on 2023-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0013_alter_case_options_alter_cpu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='formfactor',
            field=models.IntegerField(default=0),
        ),
    ]
