# Generated by Django 4.0.3 on 2023-05-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0014_alter_motherboard_formfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='ddr_gen',
            field=models.CharField(default='DDR4', max_length=15),
        ),
        migrations.AddField(
            model_name='ram',
            name='ddr_gen',
            field=models.CharField(default='DDR4', max_length=10),
        ),
    ]
