# Generated by Django 4.0.3 on 2023-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0015_motherboard_ddr_gen_ram_ddr_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='gen',
            field=models.CharField(max_length=30),
        ),
    ]
