# Generated by Django 4.0.3 on 2023-05-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0016_alter_motherboard_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='capacity',
            field=models.IntegerField(default=1000),
        ),
    ]
